name: Java CI with Maven
#a
on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'backend/user-auth-service/**'
      - 'backend/submission-result-service/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'dev'
      - 'main'
    paths:
      - 'backend/user-auth-service/**'
      - 'backend/submission-result-service/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build User Auth Service
        working-directory: backend/user-auth-service
        run: mvn -B -U -DskipTests=false clean verify

      - name: Build Submission Result Service
        working-directory: backend/submission-result-service
        run: mvn -B -U -DskipTests=false clean verify
