name: Build and Push Notification Service Docker Image

on:
  push:
    branches:
      - main
      - dev
      - dev-sync
    paths:
      - 'backend/notification-service/**'
      - '.github/workflows/notification-service-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the code
      - uses: actions/checkout@v4
      
      # Set up Docker Buildx for multi-platform builds
      - uses: docker/setup-buildx-action@v2
      
      # Log in to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push Docker image
      - uses: docker/build-push-action@v4
        with:
          context: ./backend/notification-service
          file: ./backend/notification-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
            ${{ secrets.DOCKER_USERNAME }}/notification-service:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Optional: Run tests before building Docker image
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run unit tests
        working-directory: ./backend/notification-service
        run: go test -v ./...
      
      - name: Run test coverage
        working-directory: ./backend/notification-service
        run: go test -v -coverprofile=coverage.out ./...
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./backend/notification-service/coverage.out
          flags: notification-service
